name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: >
        sudo apt-get install
        libdbus-1-dev
        libusb-dev
        libhidapi-dev
        libhidapi-hidraw0
        pkg-config
    - name: Build
      working-directory: ./razer_control_gui
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./razer_control_gui
      run: cargo test --verbose
